anguage: node_js
node_js:
 -  "7"

dist: trusty
sudo: required

addons:
  sonarqube:
    organization: "chowanioksource"
    branches :
      - master

jdk:
  - oraclejdk8

script:
  - sonar-scanner
  - yarn test

cache:
  directories:
    - '$HOME/.sonar/cache'
