anguage: node_js
node_js:
 -  "7"

dist: trusty
sudo: false
group: edge

addons:
  sonarqube:
    organization: "chowanioksource"
    branches :
      - master
    token:
      secure: DWqGB46D4ccHh4qRTH5invmadVraXC+tPLO6Tbst5CEfT0fKA0XKoEPh+8lx8MAMr9Lpu5oDNwHKLbICFMX/Sqa7Car0cGPexsk44VNP0O+S5LC6a2WHJvc463O6NQP5J/ExFdmMgrkuJiomNvYRlKj7IFehJUT04FxXfBmQZ9H4srVMyDm+YIodaSpFKqUKNFPf8iBwjNKAEvMVlLhRZX+89acG0QmOp5FuyvHKkZh9cLFhe2BYF08PGOJv75HeCMOxMjp7eRiDpabDYoyfzeACMm22cSPQMVcWzcn3/lWiy43G+f8+xzCwjO792uzWrZeVtrzxSveJ9CCtibFFW4endTYo0VRvZvmOCLNtZspL+HWTHkFmEUsVFaQ6O1ho1RL+xEof4PLYK8Y0La4mKB2IAADid7MltSaShk+VlpobMS0QSlZLv6LFyXcRhoZZ2I22ZR9zLwRmsCX1mOU+cktKfbhH1g3W/weMfIZugmz4fhFBzc5LmdkAG15jB0T3/gn8mbvVqfk2ayaVC9qEo4ELGDDuQmMVz6fcGuvaoGKiFJdKgJftOyd4YZRAbBYQ0bG2MKupa7hjUo2xmNzzvRLaNMdkeKlEfPTa7vjMAszS74G3r/IpRGKDEc+d4scGb9ppURAlHBdBhVcxQv5ZKP5WqCQddrL80TLYsdiPASI=

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
    - node_modules
